[package]
name = "kerfuś"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
num = "0.4.1"
rppal = "0.14.1"
tokio = { version = "1.33.0", features = ["full"] }
